# Generated by Django 2.0.13 on 2019-05-02 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_libro', models.CharField(max_length=12)),
                ('descripcion_libro', models.CharField(max_length=60)),
                ('id_libro', models.IntegerField()),
            ],
        ),
    ]
