# Generated by Django 2.0.13 on 2019-05-02 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebVentaLibros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre_libro',
            field=models.CharField(max_length=50),
        ),
    ]
