# Generated by Django 2.0.13 on 2019-05-07 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebVentaLibros', '0004_remove_libro_id_libro'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='cantidad_libro',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
